<?php

/**
 * @file
 * Module for Publishing an object in the sidora fba system.
 *
 * @author simonfox
 */
include_once drupal_get_path('module', 'fba_solution_pack_fba_sidora') . '/publishobject.inc';

//SFOX, FBA additions
define('MENU_CALLBACK_FBASIDORA_USERS', 'admin/settings/fbasidora/users');
define('MENU_CALLBACK_FBASIDORA_PUBLISH_COMPLETE', 'fbasidora/publish/complete');
define('MENU_CALLBACK_FBASIDORA_PUBLISH', 'fbasidora/publish');

/**
 * Provide definitions for menu callbacks.
 *
 * @return array
 *   Callback definitions
 */
function fba_solution_pack_fba_sidora_menu() {
  $items = array();

  $items[MENU_CALLBACK_FBASIDORA_PUBLISH_COMPLETE] = array(
    'title' => 'Dataset has been published',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dataset_published'),
    'access arguments' => array('view fedora collection'), //@TODO Investigate if this permission makes sense.
    'type' => MENU_CALLBACK,
  );
  $items[MENU_CALLBACK_FBASIDORA_PUBLISH] = array(
    'title' => 'Publish Object',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fba_solution_pack_fba_sidora_form_publish'),
    'access arguments' => array('view fedora collection'),
    'type' => MENU_CALLBACK,
  );
  $items[MENU_CALLBACK_FBASIDORA_USERS] = array(
    'title' => 'List all drupal users',
    'file' => 'includes/fbasidora.inc',
    'page callback' => 'sidora_list_users',
    'access arguments' => array('view fedora collection'), //@TODO Investigate if this permission makes sense.
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Valid permissions for this module.
 *
 * @return array
 *   An array of valid permissions for the relationship_reference module
 */
function fba_solution_pack_fba_sidora_perm() {
  //return array('access fba_solution_pack_fba_sidora content');
}

function fba_solution_pack_get_namespace_from_cmodel($content_model_pid) {
  //SFOX we're not using the si namespace, so have added fba cmodels
  //horribly hard coded, need to extract this from the cmodel ideally
  switch ($content_model_pid) {
    //Concepts
    case 'fba:activity_cmodel': {
        $pidnamespace = 'dtcac';
        break;
      }
    case 'fba:dataset_cmodel': {
        $pidnamespace = 'dtcds';
        break;
      }
    //Resources
    case 'fba:measurement_cmodel': {
        $pidnamespace = 'dtcmt';
        break;
      }
    case 'fba:analysis_cmodel': {
        $pidnamespace = 'dtcan';
        break;
      }
    case 'fba:litreview_cmodel': {
        $pidnamespace = 'dtclr';
        break;
      }
    case 'fba:simulation_cmodel': {
        $pidnamespace = 'dtcsi';
        break;
      }
    case 'fba:synthesis_cmodel': {
        $pidnamespace = 'dtcsy';
        break;
      }
    //Supplementary File Resources
    case 'fba:supp_basic_image_cmodel': {
        $pidnamespace = 'dtcbim';
        break;
      }
    case 'fba:supp_large_image_cmodel': {
        $pidnamespace = 'dtclim';
        break;
      }
    case 'fba:supp_pdf_cmodel': {
        $pidnamespace = 'dtcpdf';
        break;
      }
    case 'fba:supp_text_cmodel': {
        $pidnamespace = 'dtctxt';
        break;
      }
    case 'fba:supp_excel_cmodel': {
        $pidnamespace = 'dtcxl';
        break;
      }
    case 'fba:supp_word_cmodel': {
        $pidnamespace = 'dtcwd';
        break;
      }
    default: {
        $pidnamespace = 'dtcuc'; //
      }
  }
  return $pidnamespace;
}

/**
 * Gets all the required data.
 *
 * @return array
 *   The definitions of all the required content models and collections to be ingested.
 */
function fba_solution_pack_fba_sidora_required_fedora_objects() {
  module_load_include('inc', 'fedora_repository', 'fedora_repository.solutionpacks');
  $module_path = drupal_get_path('module', 'fba_solution_pack_fba_sidora');
//SFOX NOTE!!! the object details tab viewing facility MUST be switched off in /admin/settings/fedora_repository
  return array(
    'fba_solution_pack_fba_sidora' => array(
      'module' => 'fba_solution_pack_fba_sidora',
      'title' => 'FBA Sidora Required Content',
      'objects' => array(
        array(
          'pid' => 'fba:licence_cmodel',
          'label' => 'FBA Licence Resource',
          'datastreams' => array(
            array(
              'dsid' => 'ISLANDORACM',
              'datastream_file' => "$module_path/licence_cmodel/ISLANDORACM.xml",
              'dsversion' => 1,
              'mimetype' => 'text/xml'
            ),
            array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/licence_cmodel/POLICY.xml",
              'dsversion' => 1,
              'mimetype' => 'text/xml'
            ),
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/licence_cmodel/COLLECTION_POLICY.xml",
              'dsversion' => 1,
              'mimetype' => 'text/xml'
            ),
          )
        ),
        //collections
        array(
          'pid' => 'fba:licence_collection',
          'label' => 'FBA Licence Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => variable_get('fedora_repository_pid', 'fba:root'),
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/fba_licence_collection_policy.xml",
            ),
            array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/licence_cmodel/POLICY.xml",
              'dsversion' => 1,
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        //licences
        array(
          'pid' => 'fbalicence:1',
          'label' => 'FBA Licence',
          'cmodel' => 'fba:licence_cmodel',
          'parent' => 'fba:licence_collection',
          'datastreams' => array(
            array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/licence_cmodel/POLICY.xml",
              'dsversion' => 1,
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        //AEDA collections
        array(
          'pid' => 'aeda:collection',
          'label' => 'AEDA Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'islandora:root',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/aeda_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/collection_policies/TN.png",
            ), array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/security_policies/anonymous_view_policy.xml",
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        array(
          'pid' => 'ast:collection',
          'label' => 'Atlantic Salmon Trust Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'aeda:collection',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/ast_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/collection_policies/TN.png",
            ), array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/security_policies/anonymous_view_policy.xml",
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        array(
          'pid' => 'defra:collection',
          'label' => 'DEFRA Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'aeda:collection',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/defra_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/collection_policies/TN.png",
            ), array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/security_policies/anonymous_view_policy.xml",
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        array(
          'pid' => 'ea:collection',
          'label' => 'Environment Agency Collections',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'aeda:collection',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/ea_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/collection_policies/TN.png",
            ), array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/security_policies/anonymous_view_policy.xml",
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        array(
          'pid' => 'fba:collection',
          'label' => 'FBA Collections',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'aeda:collection',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/fba_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/collection_policies/TN.png",
            ), array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/security_policies/anonymous_view_policy.xml",
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        //end of level 1 collections
        //start of defra subcollections
        array(
          'pid' => 'dtc:collection',
          'label' => 'DTC Data',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'defra:collection',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/dtc_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/collection_policies/TN.png",
            ), array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/security_policies/anonymous_view_policy.xml",
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        array(
          'pid' => 'ghg:collection',
          'label' => 'GHG Data',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'defra:collection',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/ghg_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/collection_policies/TN.png",
            ), array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/security_policies/anonymous_view_policy.xml",
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        array(
          'pid' => 'dtcavon:collection',
          'label' => 'Avon DTC',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'dtc:collection',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/dtcavon_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/collection_policies/TN.png",
            ), array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/security_policies/anonymous_view_policy.xml",
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        array(
          'pid' => 'dtceden:collection',
          'label' => 'Eden DTC',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'dtc:collection',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/dtceden_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/collection_policies/TN.png",
            ), array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/security_policies/anonymous_view_policy.xml",
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        array(
          'pid' => 'dtcwensum:collection',
          'label' => 'Wensum DTC',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'dtc:collection',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/dtcwensum_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/collection_policies/TN.png",
            ),
            array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/security_policies/anonymous_view_policy.xml",
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        //ea collections
        array(
          'pid' => 'eachryso:collection',
          'label' => 'Chrysophytes Database',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'ea:collection',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/eachryso_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/collection_policies/TN.png",
            ), array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/security_policies/anonymous_view_policy.xml",
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        array(
          'pid' => 'ealit:collection',
          'label' => 'Grey Literature',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'ea:collection',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/ealit_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/collection_policies/TN.png",
            ), array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/security_policies/anonymous_view_policy.xml",
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        //fba collections
        array(
          'pid' => 'fbads:collection',
          'label' => 'Datasets',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'fba:collection',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/fbads_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/collection_policies/TN.png",
            ), array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/security_policies/anonymous_view_policy.xml",
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        array(
          'pid' => 'fbaia:collection',
          'label' => 'FBA Image Archive',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'fba:collection',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/fbaia_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/collection_policies/TN.png",
            ), array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/security_policies/anonymous_view_policy.xml",
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        array(
          'pid' => 'fbalc:collection',
          'label' => 'Library Catalogue',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'fba:collection',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/fbalc_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/collection_policies/TN.png",
            ), array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/security_policies/anonymous_view_policy.xml",
              'mimetype' => 'text/xml'
            ),
          ),
        ),
        array(
          'pid' => 'fbauc:collection',
          'label' => 'Unpublished Collections',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'fba:collection',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/fbauc_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/collection_policies/TN.png",
            ), array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/security_policies/anonymous_view_policy.xml",
              'mimetype' => 'text/xml'
            ),
          ),
        ),
      //End of definitions
      ),
    )
  );
}
