<?php

/**
 * @file
 * Module for Publishing an object in the sidora fba system.
 *
 * @author simonfox
 */
include_once drupal_get_path('module', 'fba_solution_pack_fba_sidora') . '/publishobject.inc';

//SFOX, FBA additions
define('MENU_CALLBACK_FBASIDORA_USERS', 'admin/settings/fbasidora/users');
define('MENU_CALLBACK_FBASIDORA_PUBLISH_COMPLETE', 'fbasidora/publish/complete');
define('MENU_CALLBACK_FBASIDORA_PUBLISH', 'fbasidora/publish');

/**
 * Provide definitions for menu callbacks.
 *
 * @return array
 *   Callback definitions
 */
function fba_solution_pack_fba_sidora_menu() {
  $items = array();

  $items[MENU_CALLBACK_FBASIDORA_PUBLISH_COMPLETE] = array(
    'title' => 'Dataset has been published',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dataset_published'),
    'access arguments' => array('view fedora collection'), //@TODO Investigate if this permission makes sense.
    'type' => MENU_CALLBACK,
  );
  $items[MENU_CALLBACK_FBASIDORA_PUBLISH] = array(
    'title' => 'Publish Object',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fba_solution_pack_fba_sidora_form_publish'),
    'access arguments' => array('view fedora collection'),
    'type' => MENU_CALLBACK,
  );
  $items[MENU_CALLBACK_FBASIDORA_USERS] = array(
    'title' => 'List all drupal users',
    'file' => 'includes/fbasidora.inc',
    'page callback' => 'sidora_list_users',
    'access arguments' => array('view fedora collection'), //@TODO Investigate if this permission makes sense.
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Valid permissions for this module.
 *
 * @return array
 *   An array of valid permissions for the relationship_reference module
 */
function fba_solution_pack_fba_sidora_perm() {
  //return array('access fba_solution_pack_fba_sidora content');
}

function fba_solution_pack_get_namespace_from_cmodel($content_model_pid) {
  //SFOX we're not using the si namespace, so have added fba cmodels
  //horribly hard coded, need to extract this from the cmodel ideally
  switch ($content_model_pid) {
    //Concepts
    case 'fba:activity_cmodel': {
        $pidnamespace = 'dtcac';
        break;
      }
    case 'fba:dataset_cmodel': {
        $pidnamespace = 'dtcds';
        break;
      }
    //Resources
    case 'fba:measurement_cmodel': {
        $pidnamespace = 'dtcmt';
        break;
      }
    case 'fba:analysis_cmodel': {
        $pidnamespace = 'dtcan';
        break;
      }
    case 'fba:litreview_cmodel': {
        $pidnamespace = 'dtclr';
        break;
      }
    case 'fba:simulation_cmodel': {
        $pidnamespace = 'dtcsi';
        break;
      }
    case 'fba:synthesis_cmodel': {
        $pidnamespace = 'dtcsy';
        break;
      }
    //Supplementary File Resources
    case 'fba:supp_basic_image_cmodel': {
        $pidnamespace = 'dtcbim';
        break;
      }
    case 'fba:supp_large_image_cmodel': {
        $pidnamespace = 'dtclim';
        break;
      }
    case 'fba:supp_pdf_cmodel': {
        $pidnamespace = 'dtcpdf';
        break;
      }
    case 'fba:supp_text_cmodel': {
        $pidnamespace = 'dtctxt';
        break;
      }
    case 'fba:supp_excel_cmodel': {
        $pidnamespace = 'dtcxl';
        break;
      }
    case 'fba:supp_word_cmodel': {
        $pidnamespace = 'dtcwd';
        break;
      }
    default: {
        $pidnamespace = 'dtcuc'; //
      }
  }
  return $pidnamespace;
}

/**
 * Gets all the required data.
 *
 * @return array
 *   The definitions of all the required content models and collections to be ingested.
 */
function fba_solution_pack_fba_sidora_required_fedora_objects() {
  module_load_include('inc', 'fedora_repository', 'fedora_repository.solutionpacks');
  $module_path = drupal_get_path('module', 'fba_solution_pack_fba_sidora');

  return array(
    'fba_solution_pack_fba_sidora' => array(
      'module' => 'fba_solution_pack_fba_sidora',
      'title' => 'FBA Sidora Required Content',
      'objects' => array(
        array(
          'pid' => 'fba:license_cmodel',
          'label' => 'FBA License Resource',
          'datastreams' => array(
            array(
              'dsid' => 'ISLANDORACM',
              'datastream_file' => "$module_path/license_cmodel/ISLANDORACM.xml",
              'dsversion' => 1,
              'mimetype' => 'text/xml'
            ),
            array(
              'dsid' => 'POLICY',
              'datastream_file' => "$module_path/license_cmodel/POLICY.xml",
              'dsversion' => 1,
              'mimetype' => 'text/xml'
            ),
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/license_cmodel/COLLECTION_POLICY.xml",
              'dsversion' => 1,
              'mimetype' => 'text/xml'
            ),
          )
        ),
        //collections
        array(
          'pid' => 'fba:license_collection',
          'label' => 'FBA License Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => variable_get('fedora_repository_pid', 'fba:root'),
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/collection_policies/fba_license_collection_policy.xml",
            ),
          ),
        ),
        //licenses
        array(
          'pid' => 'fbalicense:1',
          'label' => 'FBA License',
          'cmodel' => 'fba:license_cmodel',
          'parent' => 'fba:license_collection',
          'datastreams' => array(
          ),
        ),
      //End of definitions
      ),
    )
  );
}
